
    
name: main
on:
  commit:
    branches:
      - main
jobs:
  # build web
  build_web:
    name: build_web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subsito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web
    
